[book]
title = "Asynchronous Programming in Rust"
language = "en"
authors = ["Taylor Cramer"]

[build]
create-missing = false

[preprocess.links]

[output.html]

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false

[[output.i18n.translations]]
title = "Асинхронное программирование на Rust"
language = "ru"

[[output.i18n.translations]]
title = "Asynchronous Programming in Rust"
language = "zh-cn"

[[output.i18n.translations]]
title = "Rust 非同步程式設計"
language = "zh-tw"
